---
- name: CentOS
  include: centos.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version >=7

- name: Ubuntu
  include: ubuntu.yml
  when: ansible_distribution =="Ubuntu"