---
- name: Include Vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install Packages
  package:
    name: "{{ PackageName }}"

- name: Apache main Configuration
  template:
    src: httpd.conf.j2
    dest: "{{ DocumentRoot }}/conf/{{ ServiceName }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: "restart {{ ServiceName }}"

- name: Apache VirtualHost Configuration
  template:
    src: virtualhost.conf.j2
    dest: "{{ DocumentRoot }}/conf.d/virtualhosts.conf"
    owner: root
    group: root
    mode: 0644
  notify: "restart {{ ServiceName }}"
  with_items: VirtualHost